[build]
command = "npm run build"
publish = "dist"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[redirects]]
from = "/paper/*"
to = "/.netlify/functions/paper/:splat"
status = 200

[[redirects]]
from = "/paper"
to = "/.netlify/functions/paper"
status = 200
